version: "3.0"
services:
  app:
    container_name: app
    image: app
    env_file:
      - env_vars/docker.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /root/MyProjects/luchanos_oxford_university/info.log:/info.log