"""comment

Revision ID: aea727152688
Revises: 0ea05074eaf8
Create Date: 2023-10-06 21:36:17.352292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea727152688'
down_revision = '0ea05074eaf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_username')
    # ### end Alembic commands ###
